title = "Chukwuebuka Osuji"
baseURL = "https://osuji.netlify.app/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false 
publishDir = "public"      

[params]
  author = "Chukwuebuka Osuji"
  description = "Information Scientist and self-taught developer"
  favicon = "favicon.ico" 
  [params.footer]
    text = "By Chukwuebuka Osuji"
    url = "https://github.com/atlasmoth"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  
  
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 1
  [[menu.main]]
    name = "Reading"
    url = "/reading"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files